/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pizza;

import java.awt.Color;
import java.sql.*;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ralph
 */
public class Pizza extends javax.swing.JFrame {
    private int customerID;
    
    /**
     * Creates new form Pizza
     */
    public Pizza(int customerID) {
        this.customerID = customerID;
        initComponents();
    }

    DefaultTableModel model;
    String item;
    int price;
    int qty;
    int sum;
    int size;
    int totalMoneyAmount;
    int totalChangeAmount;
    private String url = "jdbc:mysql://localhost:3306/pizza?zeroDateTimeBehavior=CONVERT_TO_NULL";
    private String username = "root";
    private String password = "";
    public Connection con;
    public Statement state;
    public ResultSet result;
    public PreparedStatement prepare;
    int pizzaID;
    String pizzaFlavor;
    int pizzaSizeInch;
    int pizzaPrice;
    int pizzaStocks;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        newPizzaPanel = new javax.swing.JPanel();
        tripleCheesySupreme = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        tcpButton = new javax.swing.JButton();
        tcp9 = new javax.swing.JRadioButton();
        tcp12 = new javax.swing.JRadioButton();
        tcpQty = new javax.swing.JSpinner();
        seafoodPizza = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        sfsButton = new javax.swing.JButton();
        sfs9 = new javax.swing.JRadioButton();
        sfs12 = new javax.swing.JRadioButton();
        sfsQty = new javax.swing.JSpinner();
        superSupreme = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        ssButton = new javax.swing.JButton();
        ss9 = new javax.swing.JRadioButton();
        ss12 = new javax.swing.JRadioButton();
        ssQty = new javax.swing.JSpinner();
        cheeseSupreme = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        csButton = new javax.swing.JButton();
        cs9 = new javax.swing.JRadioButton();
        cs12 = new javax.swing.JRadioButton();
        csQty = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        logoutButton = new javax.swing.JLabel();
        deleteItem = new javax.swing.JButton();
        paymentMode = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        moneyAmount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        totalChange = new javax.swing.JLabel();
        paymentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizza Ordering");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setText("House Of Crust");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        newPizzaPanel.setBackground(new java.awt.Color(204, 204, 204));
        newPizzaPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tripleCheesySupreme.setPreferredSize(new java.awt.Dimension(175, 175));

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        tcpButton.setText("Add to Cart");
        tcpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcpButtonActionPerformed(evt);
            }
        });

        tcp9.setText("Triple Cheesy Supreme 9 Inches");

        tcp12.setText("Triple Cheesy Supreme 12 Inches");

        javax.swing.GroupLayout tripleCheesySupremeLayout = new javax.swing.GroupLayout(tripleCheesySupreme);
        tripleCheesySupreme.setLayout(tripleCheesySupremeLayout);
        tripleCheesySupremeLayout.setHorizontalGroup(
            tripleCheesySupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tripleCheesySupremeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tripleCheesySupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tripleCheesySupremeLayout.createSequentialGroup()
                        .addGroup(tripleCheesySupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tcp12)
                            .addComponent(tcp9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tripleCheesySupremeLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(tcpButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tcpQty)))
                .addContainerGap())
        );
        tripleCheesySupremeLayout.setVerticalGroup(
            tripleCheesySupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tripleCheesySupremeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tcp9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tcp12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tripleCheesySupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tcpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tcpQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        seafoodPizza.setPreferredSize(new java.awt.Dimension(175, 175));

        jPanel6.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        sfsButton.setText("Add to Cart");
        sfsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfsButtonActionPerformed(evt);
            }
        });

        sfs9.setText("Seafood Supreme 9 Inches");

        sfs12.setText("Seafood Supreme 12 Inches");

        javax.swing.GroupLayout seafoodPizzaLayout = new javax.swing.GroupLayout(seafoodPizza);
        seafoodPizza.setLayout(seafoodPizzaLayout);
        seafoodPizzaLayout.setHorizontalGroup(
            seafoodPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seafoodPizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seafoodPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(seafoodPizzaLayout.createSequentialGroup()
                        .addGroup(seafoodPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sfs12)
                            .addComponent(sfs9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, seafoodPizzaLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(sfsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sfsQty)))
                .addContainerGap())
        );
        seafoodPizzaLayout.setVerticalGroup(
            seafoodPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seafoodPizzaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sfs9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sfs12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(seafoodPizzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sfsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sfsQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        superSupreme.setPreferredSize(new java.awt.Dimension(175, 175));

        jPanel7.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        ssButton.setText("Add to Cart");
        ssButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssButtonActionPerformed(evt);
            }
        });

        ss9.setText("Super Supreme 9 Inches");

        ss12.setText("Super Supreme 12 Inches");

        javax.swing.GroupLayout superSupremeLayout = new javax.swing.GroupLayout(superSupreme);
        superSupreme.setLayout(superSupremeLayout);
        superSupremeLayout.setHorizontalGroup(
            superSupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superSupremeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(superSupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(superSupremeLayout.createSequentialGroup()
                        .addGroup(superSupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ss12)
                            .addComponent(ss9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, superSupremeLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(ssButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ssQty)))
                .addContainerGap())
        );
        superSupremeLayout.setVerticalGroup(
            superSupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superSupremeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ss9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ss12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(superSupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ssQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cheeseSupreme.setPreferredSize(new java.awt.Dimension(175, 175));

        jPanel8.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        csButton.setText("Add to Cart");
        csButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csButtonActionPerformed(evt);
            }
        });

        cs9.setText("Cheese Supreme 9 Inches");

        cs12.setText("Cheese Supreme 12 Inches");

        javax.swing.GroupLayout cheeseSupremeLayout = new javax.swing.GroupLayout(cheeseSupreme);
        cheeseSupreme.setLayout(cheeseSupremeLayout);
        cheeseSupremeLayout.setHorizontalGroup(
            cheeseSupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cheeseSupremeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cheeseSupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(cheeseSupremeLayout.createSequentialGroup()
                        .addGroup(cheeseSupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cs12)
                            .addComponent(cs9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cheeseSupremeLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(csButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(csQty)))
                .addContainerGap())
        );
        cheeseSupremeLayout.setVerticalGroup(
            cheeseSupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cheeseSupremeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cs9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cs12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cheeseSupremeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(csButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(csQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout newPizzaPanelLayout = new javax.swing.GroupLayout(newPizzaPanel);
        newPizzaPanel.setLayout(newPizzaPanelLayout);
        newPizzaPanelLayout.setHorizontalGroup(
            newPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPizzaPanelLayout.createSequentialGroup()
                .addGroup(newPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newPizzaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(superSupreme, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cheeseSupreme, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newPizzaPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(tripleCheesySupreme, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seafoodPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        newPizzaPanelLayout.setVerticalGroup(
            newPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newPizzaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tripleCheesySupreme, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seafoodPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newPizzaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cheeseSupreme, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(superSupreme, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "pizzaID", "Order", "Inch", "Price", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(75);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(75);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(75);
        }

        logoutButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutButtonMouseClicked(evt);
            }
        });

        deleteItem.setBackground(new java.awt.Color(153, 0, 0));
        deleteItem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        deleteItem.setForeground(new java.awt.Color(255, 255, 255));
        deleteItem.setText("Delete Item");
        deleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemActionPerformed(evt);
            }
        });

        paymentMode.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setText("Total:  ");

        totalPrice.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        totalPrice.setText("0");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Amount:");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("Change:");

        totalChange.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        totalChange.setText("0");

        paymentButton.setBackground(new java.awt.Color(153, 153, 153));
        paymentButton.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        paymentButton.setForeground(new java.awt.Color(255, 255, 255));
        paymentButton.setText("Confirm Payment");
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paymentModeLayout = new javax.swing.GroupLayout(paymentMode);
        paymentMode.setLayout(paymentModeLayout);
        paymentModeLayout.setHorizontalGroup(
            paymentModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentModeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentModeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPrice))
                    .addGroup(paymentModeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moneyAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paymentModeLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalChange))
                    .addGroup(paymentModeLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(paymentButton)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        paymentModeLayout.setVerticalGroup(
            paymentModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentModeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paymentModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totalPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(moneyAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentModeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(totalChange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paymentButton)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPizzaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                        .addComponent(logoutButton)
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 238, Short.MAX_VALUE)
                        .addComponent(deleteItem)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paymentMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(newPizzaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paymentMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tcpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcpButtonActionPerformed
         int pizzaID =0; 
        if (tcp9.isSelected() == true) {
            item = "Triple Cheesy Supreme";
            size = 9;
            price = 399;
            pizzaID =1;

        } else if (tcp12.isSelected() == true) {
            item = "Triple Cheesy Supreme";
            size = 12;
            price = 629;
             pizzaID =2;
        }

        qty = Integer.parseInt(tcpQty.getValue().toString());

        if (qty > 0) {
            int total = qty * price;

            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                pizzaID,
                item,
                size,
                total,
                qty
            });

            totalPricePropertyChange(null);
        }
    }//GEN-LAST:event_tcpButtonActionPerformed

    private void totalPricePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_totalPricesPropertyChange

        
        sum = 0;

        for (int i = 0; i < jTable1.getRowCount(); i++) {
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }
        totalPrice.setText(Integer.toString(sum));
       
    }//GEN-LAST:event_totalPricesPropertyChange

    private void sfsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfsButtonActionPerformed
        int pizzaID =0;
        
        if (sfs9.isSelected() == true) {
            item = "Seafood Supreme";
            size = 9;
            price = 399;
            pizzaID = 3;

        } else if (sfs12.isSelected() == true) {
            item = "Seafood Supreme";
            size = 12;
            price = 629;
            pizzaID=4;
        }

        qty = Integer.parseInt(sfsQty.getValue().toString());

        if (qty > 0) {
            int total = qty * price;

            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                pizzaID,
                item,
                size,
                total,
                qty
            });

            totalPricePropertyChange(null);
        }
    }//GEN-LAST:event_sfsButtonActionPerformed

    private void ssButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssButtonActionPerformed
        int pizzaID =0 ;
        
        if(ss9.isSelected() == true) {
            item = "Super Supreme";
            size =9;
            price = 399;
            pizzaID = 5;

        } else if (ss12.isSelected() == true) {
            item = "Super Supreme";
            size =12;
            price = 629;
            pizzaID=6;
        }

        qty = Integer.parseInt(ssQty.getValue().toString());

        if (qty > 0) {
            int total = qty * price;

            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                pizzaID,
                item,
                size,
                total,
                qty
            });

            totalPricePropertyChange(null);
        }
    }//GEN-LAST:event_ssButtonActionPerformed

    private void csButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csButtonActionPerformed
       int pizzaID=0;
        
        if (cs9.isSelected() == true) {
            item = "Cheese Supreme";
            size = 9;
            price = 399;
            pizzaID=7;

        } else if (cs12.isSelected() == true) {
            item = "Cheese Supreme";
            size =12;
            price = 589;
            pizzaID=8;
        }

        qty = Integer.parseInt(csQty.getValue().toString());

        if (qty > 0) {
            int total = qty * price;

            model = (DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{
                pizzaID,
                item,
                size,
                total,
                qty
            });

            totalPricePropertyChange(null);
        }
    }//GEN-LAST:event_csButtonActionPerformed

    private void logoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseClicked
        LogIn login = new LogIn();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonMouseClicked

    private void deleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemActionPerformed
        
        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow >=0) {
             model.removeRow(selectedRow);
             
             int sum =0;
        for(int i=0;i<jTable1.getRowCount();i++){
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
        }
        totalPrice.setText(Integer.toString(sum));
        }      
    }//GEN-LAST:event_deleteItemActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        
        String totalMoneyAmountText = moneyAmount.getText().trim();
    
    if (totalMoneyAmountText.isEmpty()) {
        return;
    }
    
    int totalMoneyAmount;
    try {
        totalMoneyAmount = Integer.parseInt(totalMoneyAmountText);
    } catch (NumberFormatException e) {
        return;
    }

    if (totalMoneyAmount > sum) {
        totalChangeAmount = totalMoneyAmount - sum;
        totalChange.setText(Integer.toString(totalChangeAmount));

        Connection con = null;
        PreparedStatement prepare = null;
        PreparedStatement orderItemsPrepare = null;
        PreparedStatement updatePizzaPrepare = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url, username, password);

            String sql = "INSERT INTO orders (customerID, pizzaID, customerTotal, customerPayment, customerChange) VALUES (?, ?, ?, ?, ?)";
            prepare = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            int customerID = this.customerID;
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int orderID = 0;

            for (int i = 0; i < model.getRowCount(); i++) {
                int pizzaID = Integer.parseInt(model.getValueAt(i, 0).toString());
                int totalPrice = (int) model.getValueAt(i, 3);

                prepare.setInt(1, customerID);
                prepare.setInt(2, pizzaID);
                prepare.setInt(3, totalPrice);
                prepare.setInt(4, totalMoneyAmount);
                prepare.setInt(5, totalChangeAmount);

                prepare.addBatch();
            }

            prepare.executeBatch();

            ResultSet generatedKeys = prepare.getGeneratedKeys();
            if (generatedKeys.next()) {
                orderID = generatedKeys.getInt(1);
            }

            String orderItemsSql = "INSERT INTO ordereditems (orderID, pizzaID, quantity) VALUES (?, ?, ?)";
            orderItemsPrepare = con.prepareStatement(orderItemsSql);

            for (int i = 0; i < model.getRowCount(); i++) {
                int pizzaID = Integer.parseInt(model.getValueAt(i, 0).toString());
                int quantity = Integer.parseInt(model.getValueAt(i, 4).toString()); // Assuming quantity is in the second column

                orderItemsPrepare.setInt(1, orderID);
                orderItemsPrepare.setInt(2, pizzaID);
                orderItemsPrepare.setInt(3, quantity);

                orderItemsPrepare.addBatch();
            }

            orderItemsPrepare.executeBatch();

            String updatePizzaSql = "UPDATE pizza p JOIN (SELECT pizzaID, quantity AS totalOrdered FROM ordereditems WHERE orderID = ?) ordereditems ON p.pizzaID = ordereditems.pizzaID SET p.Stocks = p.Stocks - ordereditems.totalOrdered";
            updatePizzaPrepare = con.prepareStatement(updatePizzaSql);
            updatePizzaPrepare.setInt(1, orderID);
            updatePizzaPrepare.executeUpdate();

        } catch (Exception e) {
            e.printStackTrace();
            } 
        } 
    }//GEN-LAST:event_paymentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza(1).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cheeseSupreme;
    private javax.swing.JRadioButton cs12;
    private javax.swing.JRadioButton cs9;
    private javax.swing.JButton csButton;
    private javax.swing.JSpinner csQty;
    private javax.swing.JButton deleteItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logoutButton;
    private javax.swing.JTextField moneyAmount;
    private javax.swing.JPanel newPizzaPanel;
    private javax.swing.JButton paymentButton;
    private javax.swing.JPanel paymentMode;
    private javax.swing.JPanel seafoodPizza;
    private javax.swing.JRadioButton sfs12;
    private javax.swing.JRadioButton sfs9;
    private javax.swing.JButton sfsButton;
    private javax.swing.JSpinner sfsQty;
    private javax.swing.JRadioButton ss12;
    private javax.swing.JRadioButton ss9;
    private javax.swing.JButton ssButton;
    private javax.swing.JSpinner ssQty;
    private javax.swing.JPanel superSupreme;
    private javax.swing.JRadioButton tcp12;
    private javax.swing.JRadioButton tcp9;
    private javax.swing.JButton tcpButton;
    private javax.swing.JSpinner tcpQty;
    private javax.swing.JLabel totalChange;
    private javax.swing.JLabel totalPrice;
    private javax.swing.JPanel tripleCheesySupreme;
    // End of variables declaration//GEN-END:variables

}
